@echo off
echo Killing any existing frontend processes...
taskkill /f /fi "WINDOWTITLE eq vite" /im node.exe 2>nul

echo Cleaning node_modules cache...
if exist .\.vite rmdir /s /q .\.vite

echo Installing dependencies if needed...
if not exist .\node_modules (
  echo Node modules not found. Installing dependencies...
  npm install
)

echo Starting frontend...
npm run dev
